### ISSUE TITLE
List the station links of B2/B3 on the homebar

### ISSUE THREAD

**Issue by LDQMF** [doublechiang/QMFRacklog#25]

**Comment by doublechiang** [comment]
LD,
please deploy to the running server (the user can see the change) then close it, thanks.

**Comment by doublechiang** [comment]
duplicate with #27

**Comment by doublechiang** [comment]
@LDQMF ,

I am sorry for not giving clear instruction.
I will use 'use case' instead.
Before the banner is 
```Log Search | DIMM Error Locator```

Your current changes are 
```Log Search | DIMM Error Locator | B2 | B3```, which B2 is actually duplicate to Log Search.

I would proposal you make a second banner bar.
```Log Search | DIMM Error Locator```
```B2 | B3```
 (You can make B3 as default since we are moving to B3 majority)

or one banner as. 
```B2 Log Search | B3 Log Search | DIMM Error Locator```.

Please raise any question if you have some uncertainty
